### List employees

GET http://localhost:8080/api/employees
Accept: application/json

### Find employee by id

GET http://localhost:8080/api/employees/1
Accept: application/json

### Find employee by illegal id

GET http://localhost:8080/api/employees/34252434625623
Accept: application/json

### List employees with filter "Jane"

GET http://localhost:8080/api/employees?prefix=jane
Accept: application/json

### Create employee

POST http://localhost:8080/api/employees
Content-Type: application/json
Accept: application/json

{
"name": "Jane Doe"
}

### Update employee

PUT http://localhost:8080/api/employees/1
Content-Type: application/json
Accept: application/json

{
  "name": "John Joe Doe"
}

### Delete employee

DELETE http://localhost:8080/api/employees/1

### Create employee with blank name

POST http://localhost:8080/api/employees
Content-Type: application/json
Accept: application/json

{
  "name": "   "
}